const fs=require('fs');
const assert=require('assert');
function read(p){return fs.readFileSync(p,'utf8')}
const index=read('public/index.html');
const app=read('public/app-1.9.1.js');
const css=read('public/styles-1.9.1.css');
const server=read('server.js');
const bat=read('AGGIORNA_GITHUB.bat');
const ps1=read('AGGIORNA_GITHUB.ps1');
const pkg=JSON.parse(read('package.json'));
assert.equal(pkg.version,'1.9.1');
assert(index.includes('/app-1.9.1.js') && index.includes('/styles-1.9.1.css'));
assert(app.includes('diceShell') && app.includes('playResolutionSequence') && app.includes('duelDiceReveal'));
assert(app.includes('buildBadge">v1.9.1'));
assert(css.includes('@keyframes diceThrow') && css.includes('.weatherFx') && css.includes('.drsLive'));
assert(server.includes("version: '1.9.1'"));
assert(server.includes('attackerRoll: ar.raw') && server.includes('defenderRoll: dr.raw'));
assert(bat.includes('git clone --depth 1') && bat.includes('git push -u origin main'));
assert(bat.includes('AGGIORNA_GITHUB.ps1') && bat.includes('-File'));
assert(ps1.includes('Get-ChildItem -LiteralPath') && ps1.includes('Copy-Item -LiteralPath'));
assert(!bat.includes('Where-Object {'));
assert(bat.includes('%USERPROFILE%\\.race-command-github-repo.txt'));
assert(app.includes('raceApp') && app.includes('raceSidebar') && app.includes('raceRankingPanel') && app.includes('raceFeedPanel'));
assert(css.includes('grid-template-columns:minmax(470px,32%) minmax(560px,45%) minmax(330px,23%)'));
assert(css.includes('grid-template-columns:repeat(2,minmax(0,1fr))!important'));
assert(css.includes('max-width:760px!important'));
assert(css.includes('width:calc(100vw - 20px)!important'));
assert(css.includes('.resolution.show') && css.includes('position:fixed'));
console.log('✅ Race Command 1.9.1 layout rebalance/assets/updater guard OK');
