const fs=require('fs');
const assert=require('assert');
function read(p){return fs.readFileSync(p,'utf8')}
const index=read('public/index.html');
const app=read('public/app-2.0.0.js');
const css=read('public/styles-2.0.0.css');
const server=read('server.js');
const bat=read('AGGIORNA_GITHUB.bat');
const ps1=read('AGGIORNA_GITHUB.ps1');
const pkg=JSON.parse(read('package.json'));
assert.equal(pkg.version,'2.0.0');
assert(index.includes('/app-2.0.0.js') && index.includes('/styles-2.0.0.css'));
assert(app.includes('circuitPaths') && app.includes('renderQualifying') && app.includes('gripByTrack'));
assert(app.includes('buildBadge">v2.0.0'));
assert(css.includes('.qualiChoices') && css.includes('.circuitTraits') && css.includes('.sectorStroke'));
assert(server.includes("version: '2.0.0'"));
assert(server.includes('const CIRCUITS') && server.includes('trackWetness') && server.includes('prepareQualifying'));
assert(server.includes('GOMMA FRESCA +1') && server.includes("damage='wing'"));
assert(bat.includes('git clone --depth 1') && bat.includes('git push -u origin main'));
assert(bat.includes('AGGIORNA_GITHUB.ps1') && bat.includes('-File'));
assert(ps1.includes('Get-ChildItem -LiteralPath') && ps1.includes('Copy-Item -LiteralPath'));
assert(bat.includes('%USERPROFILE%\\.race-command-github-repo.txt'));
assert(app.includes('raceApp') && app.includes('raceSidebar'));
assert(css.includes('grid-template-columns:minmax(470px,32%) minmax(560px,45%) minmax(330px,23%)'));
assert(css.includes('.resolution.show') && css.includes('position:fixed'));
console.log('✅ Race Command 2.0 release/assets/updater guard OK');
